// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy3p1VD-3vM8KrIoyxQjs_Xy9uG3sM_ds',
    appId: '1:562782037035:web:cc051ad5b90c109addf66e',
    messagingSenderId: '562782037035',
    projectId: 'aushbh-76ac2',
    authDomain: 'aushbh-76ac2.firebaseapp.com',
    storageBucket: 'aushbh-76ac2.firebasestorage.app',
    measurementId: 'G-CYRXBCNS18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqqSlLBdG-s71s8VtHIOddCYbdJE6zDyk',
    appId: '1:562782037035:android:355bcaafe877e74dddf66e',
    messagingSenderId: '562782037035',
    projectId: 'aushbh-76ac2',
    storageBucket: 'aushbh-76ac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXAXAWDRB8PSnWibL1_Xaz4VPFrWKKvO8',
    appId: '1:562782037035:ios:2bfb79a889e292d2ddf66e',
    messagingSenderId: '562782037035',
    projectId: 'aushbh-76ac2',
    storageBucket: 'aushbh-76ac2.firebasestorage.app',
    iosBundleId: 'com.example.aushbh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXAXAWDRB8PSnWibL1_Xaz4VPFrWKKvO8',
    appId: '1:562782037035:ios:2bfb79a889e292d2ddf66e',
    messagingSenderId: '562782037035',
    projectId: 'aushbh-76ac2',
    storageBucket: 'aushbh-76ac2.firebasestorage.app',
    iosBundleId: 'com.example.aushbh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy3p1VD-3vM8KrIoyxQjs_Xy9uG3sM_ds',
    appId: '1:562782037035:web:2f9c188471453103ddf66e',
    messagingSenderId: '562782037035',
    projectId: 'aushbh-76ac2',
    authDomain: 'aushbh-76ac2.firebaseapp.com',
    storageBucket: 'aushbh-76ac2.firebasestorage.app',
    measurementId: 'G-7MDC428737',
  );
}
