// File generated by FlutterFire CLI (simplified for Android and Web only).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for Android and Web.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Android and Web.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy3p1VD-3vM8KrIoyxQjs_Xy9uG3sM_ds',
    appId: '1:562782037035:web:cc051ad5b90c109addf66e',
    messagingSenderId: '562782037035',
    projectId: 'aushbh-76ac2',
    authDomain: 'aushbh-76ac2.firebaseapp.com',
    storageBucket: 'aushbh-76ac2.firebasestorage.app',
    measurementId: 'G-CYRXBCNS18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqqSlLBdG-s71s8VtHIOddCYbdJE6zDyk',
    appId: '1:562782037035:android:355bcaafe877e74dddf66e',
    messagingSenderId: '562782037035',
    projectId: 'aushbh-76ac2',
    storageBucket: 'aushbh-76ac2.firebasestorage.app',
  );
}
